name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: 'ubuntu-20.04'
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        deno: [canary]

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Set up Deno
        uses: denoland/setup-deno@v1.0.0
        with:
          deno-version: ${{ matrix.deno }}

      - name: Run tests
        run: deno test -A

      - name: Generate lcov
        shell: bash
        run: |
         deno coverage ./cov/ --lcov --exclude="test\\.(ts)" > cov.lcov
      - name: Upload coverage
        uses: codecov/codecov-action@v1
        with:
          name: ${{ matrix.os }}-${{ matrix.deno }}
          files: cov.lcov

      - name: Remove coverage report
        shell: bash
        run: |
          rm -rf ./cov/
          rm cov.lcov

  lint:
    runs-on: 'ubuntu-20.04'
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Set up Deno
        uses: denoland/setup-deno@v1.0.0

      - name: Format
        run: deno fmt --check

      - name: Lint
        run: deno lint
        